### ISSUE TITLE
show timer in the macOS menubar 

### ISSUE THREAD

**Issue by computerphilosopher** [roldanjr/pomatez#134]
**Is your feature request related to a problem? Please describe.**

Pomatez have Always on top feature already.  

but I wish I could check the timer on the menu bar.

**Describe the solution you'd like**

![image](https://user-images.githubusercontent.com/26251856/98212515-0e8b7a80-1f87-11eb-8f82-8e14b329ab38.png)

The picture above is an example of another app.

**Comment by roldanjr** [comment]
Hello @computerphilosopher . Sorry for the my very late response.

I've been so busy, so yeah.

That feature is awesome, I have tried to develop it myself before you suggested that and many of you also wanted that kind of feature, but the fact that this app is based on [ElectronJS] (https://www.electronjs.org/).
As of now, it is really near to impossible to develop that kind of functionality due to some limitations of the technology. 

Maybe soon if the ElectronJS will provide a way for that. Thanks anyway.

Have a nice day.

**Comment by computerphilosopher** [comment]
@roldanjr 

Thank you for your kind response.
