### ISSUE TITLE
Consistent use of CSS styles

### ISSUE THREAD

**Issue by beefy-raccoon** [roldanjr/pomatez#167]
I know it's a webapp that strives to be a desktop app(let) and it works fine as it is.

One thing I expected seeing a lot is the use of `cursor: pointer` on interactive elements. I wouldn't have noticed the absence of it if it wasn't to be seen on the first screen of the app: the 'Task List'.

I'll provide my findings as a list of screenshots here.

![2021-06-08_23-21-30 -- Task List Entry](https://user-images.githubusercontent.com/28466036/121259875-e6fbe800-c8b0-11eb-9ad7-8fbad2be3518.png)
--
![2021-06-08_23-27-24 -- Config](https://user-images.githubusercontent.com/28466036/121260144-3f32ea00-c8b1-11eb-8b25-dfcd3aff80f7.png)
--
![2021-06-08_23-30-41 -- Timer](https://user-images.githubusercontent.com/28466036/121260404-95a02880-c8b1-11eb-9068-b14f69e13938.png)
--
![2021-06-08_23-32-50 -- Settings top](https://user-images.githubusercontent.com/28466036/121260664-e879e000-c8b1-11eb-941d-3114865c4e35.png)
As an unrelated note here: a `title` on hover should give a short explanation of what the setting is supposed to do.

--
![2021-06-08_23-36-57 -- Settings bottom](https://user-images.githubusercontent.com/28466036/121261117-8ff71280-c8b2-11eb-975b-81097477f7d2.png)
--

Except for one place, the use of blue `color` seemed to be consistent.

Everything mentioned here may be minor but I think it would give the UI a nice final polish.

**Comment by beefy-raccoon** [comment]
Two other things on the 'Settings' that I didn't try out but could be nice: make the section headers a _little bit_ more prominent and remove the `hr` after each `:last` entry or alternatively just remove the `hr` but keep the extra padding to make headers stick out a little more.

**Comment by gillisandrew** [comment]
Hey, thanks for the feedback

>One thing I expected seeing a lot is the use of cursor: pointer on interactive elements. I wouldn't have noticed the absence of it if it wasn't to be seen on the first screen of the app: the 'Task List'.

As per both [Windows](https://docs.microsoft.com/en-us/windows/win32/uxguide/inter-mouse#pointer-shapes) and [macOS'](https://developer.apple.com/design/human-interface-guidelines/macos/user-interaction/mouse-and-trackpad/) UX guidelines, pointer is to be used only for links to webpages, files and documents or buttons that otherwise have weak affordance.

It has emerged as common practice on the web, mostly due to widespread use of anchor tags for all interactions, but is still far from being a design convention. Native apps in particular should try to adhere to the platform's design specs to ensure a consistent user experience.

Definitely worth fixing the links on the settings page but, in my opinion, the other interactive elements should remain as is.
