### ISSUE TITLE
Bug Report: Font is missing for some characters used in languages other than English

### ISSUE THREAD

**Issue by stil** [roldanjr/pomatez#182]
**Describe the bug**
pomatez does not support some special characters from languages other than English.

**To Reproduce**

Create a task with title `zażółć gęślą jaźń`. Notice that some characters fallback to other font and it looks inconsistent.

**Screenshots**

![image](https://user-images.githubusercontent.com/714004/135768849-1845c621-9f5b-44b5-886d-59d8fa01ad77.png)

**Desktop (please complete the following information):**

- OS: Win10
- App Version: 1.1.0
- Installer Used: Windows Installer

**Comment by gillisandrew** [comment]
@roldanjr I'd be happy to tackle this issue. I'd update the package font to include more glyphs but the font weight used isn't obvious. You have bold set to 500 (semi-bold) and just judging by eye it looks like you used a lightweight variant for 400 (normal). 

Anyway, if you happen to have the details for the font weights you opted for I'd be happy to repackage them and submit the pull request to close the issue. Otherwise, I can try to match it by eye.
