### ISSUE TITLE
bug: Video artefacts after hibernate mode in Ubuntu

### ISSUE THREAD

**Issue by konstantin83** [roldanjr/pomatez#249]
After Hibernate mode in Ubuntu 21.04 switch to Pomatez window and you will see something like the attached picture.

The only thing that helps is switch to any other tab and then back to Timer.

![pomatez](https://user-images.githubusercontent.com/13274062/163789405-a0bbb786-6603-46cc-a0a7-1f574384d52e.png)

**Comment by sekwah41** [comment]
I don't believe there is anything we can directly do to cause or fix this other than hoping this is fixed in a later version of electron though I will need to do a bunch of tests before upgrading the electron versions.

If you disable the transition value it may be less likely to occur on this, though we will need to look to see if it is consistent or possibly just an issue with your setup as its relating to hibernation issues.

Atm I don't have any machines setup with ubuntu so if anyone else can confirm this?

**Comment by sekwah41** [comment]
@konstantin83 could you give the linux build from here a go?

https://github.com/roldanjr/pomatez/actions/runs/2217418376

**Comment by sekwah41** [comment]
As there has been no further information or confirmations im closing ths for now
